FIX INSTALL: logger is used, but the log4php.xml file is not yet generated
Warning: file(log4php.xml) [function.file]: failed to open stream: No such file or directory in /home/content/86/10346686/html/apps/codevtt/lib/log4php/configurators/LoggerConfiguratorXml.php on line 142

Warning: implode() [function.implode]: Invalid arguments passed in /home/content/86/10346686/html/apps/codevtt/lib/log4php/configurators/LoggerConfiguratorXml.php on line 142
ERROR: Query FAILED